# Explicitly specify providers - must be at root level as an array
providers = ["...", "python"]

[phases.setup]
# python311 already includes pip, no need for python311Packages.pip
nixPkgs = ["nodejs_22", "pnpm", "python311", "chromium"]
aptPkgs = [
  "fonts-liberation",
  "libnss3",
  "libxss1",
  "libappindicator3-1",
  "libgbm1",
  "libasound2",
  "libatk-bridge2.0-0",
  "libatk1.0-0",
  "libcups2",
  "libdbus-1-3",
  "libdrm2",
  "libgdk-pixbuf2.0-0",
  "libgtk-3-0",
  "libnspr4",
  "libnss3",
  "libx11-xcb1",
  "libxcomposite1",
  "libxdamage1",
  "libxrandr2",
  "xdg-utils"
]

[phases.install]
cmds = [
  "pnpm install --no-frozen-lockfile",
  "python3 -m pip install --upgrade pip --break-system-packages",
  "python3 -m pip install selenium pillow --break-system-packages",
  "ln -sf $(which python3) /usr/local/bin/python3.11 || true",
  "python3 --version",
  "python3 -m pip list | grep selenium"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"

[variables]
NODE_ENV = "production"
PORT = "3000"

